load("//:idd.bzl", "test_pckgs_reproducibility")

# Example use of the macro
test_pckgs_reproducibility(
    name = "test",
    packages = [
        "default-jre",
        "git",
        "ca-certificates-java"
    ],
)
